apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: podinfo
  namespace: flux-system
spec:
  interval: 10m
  chart:
    spec:
      chart: podinfo
      version: "6.9.*"
      sourceRef:
        kind: HelmRepository
        name: podinfo-repo # not defined in this repo on purpose
        namespace: flux-system
